default:
  nreps: 1
  saveNData: False
  testing: "no"
  optimizer: "Nelder-Mead"
  rngSeed: 71358
  mayfStart: True
  stormFate: 0
  debug: 0
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11 # only used when saving ml vals to matrix
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out/default"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

full:
  nreps: 500
  saveNData: False
  testing: "no"
  optimizer: "Nelder-Mead"
  #rngSeed: 11153
  rngSeed: 82985
  mayfStart: False
  stormFate: 0 #0=false, 1=true, 2=use val from param list
  debug: 0
  debugLL: 0
  debugNests: 0
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

test:
  nreps: 5 
  saveNData: False
  testing: "yes"
  #optimizer: "L-BFGS-B"
  optimizer: "Nelder-Mead"
  rngSeed: 82985
  #rngSeed: 102891
  #rngSeed: 10181988
  mayfStart: False
  stormFate: 2
  debug: 3
  debugLL: 2
  debugNests: 2 
  debugM: 2
  debugObs: 2
  debugFlood: 1
  debugSummary: 2
  msg: "NEW testing combining matrix equations for all normal intervals into 1 long interval; added new function (new_mat); numint=1 [line 427] ; ALSO getting inter from new_mat() now instead of othr functions; changed matrix_poewr to loop"
  numOut: 11
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out/test"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

#####
  # likeDir: "/home/wodehouse/Projects/sim_model/out"

ctrl:
  nreps: 100
  saveNData: False
  testing: "no"
  # optimizer: "Powell"
  optimizer: "Nelder-Mead"
  rngSeed: 6131989
  mayfStart: False
  stormFate: 2
  debug: 0
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11
  useWin: False
  fnUnique: True
  likeDir: "/home/wodehouse/Projects/sim_model/out"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"
#
## nesting??
# debugging:
#   debug: 


# config = Config(nreps       = 500, 
# # config = Config(nreps       = 1, 
#                 debug       = False, 
#                 debugLL     = False, 
#                 debugNests  = False, 
#                 debugM      = False,
#                 debugObs    = False,
#                 debugFlood  = False,
#                 useWin      = False,
#                 # testing     = False,
#                 testing     = "no",
#                 fnUnique    = False,
#                 # likeFile    = fname[0], 
#                 likeFile    = " ",
#                 stormInit = "/home/wodehouse/Projects/sim_model/storm_init3.csv",
#                 likeDir = "/home/wodehouse/Projects/sim_model/out",
#                 colNames    = " ",
#                 # colNames    = fname[1],
#                 # numOut      = 21)
#                 # numOut      = 18)
#                 numOut      = 11)
