default:
  nreps: 2
  testing: "yes"
  # optimizer: "Nelder-Mead"
  # optimizer: "SLSQP"
  # optimizer: "L-BFGS-B"
  # optimizer: "BFGS"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  rngSeed: 71358
  saveNData: False
  stormFate: 1 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 3=100, 4=50, 0=use val from list
  mcType: 0 # 1=fail, 2=unk
  mark: False
  mcmc: True
  # mcmc: False
  logex: True
  rangeVar: 0
  predict: False
  survSave: "all"
  coefSave: "all"
  ndatSave: True
  plotPred: False
  obsSave: False
  predSave: False
  startParID: 1
  debug: 2
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugLogEx: 0
  debugDSR: 0
  debugSummary: 0
  optimizer: "trust-constr"
  optimGlob: True
  optimFunc: "scipy"
  other: ""
  addMC: False
  msg: ""
  numOut: 11 # only used when saving ml vals to matrix
  mcmcOld: False
  mayfStart: True
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out/default"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

# NOTE: atype can be overridden with cmd line args, but sometimes not feasible
# NOTE:   (like when calling python from R)
# NOTE: actually doesn't make sense to assign atype in config when config
# NOTE:     is chosen based on atype...

full:
  # nreps: 300
  # nreps: 500
  nreps: 200
  # logex: False
  # optimizer: "Nelder-Mead"
  # optimizer: "SLSQP"
  # optimizer: "BFGS"
  # optimizer: "L-BFGS-B"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  # testing: "yes" ## this was set to "yes" for quite a while...since july at least (aug 01 now)
  rngSeed: 71358
  #rngSeed: 7131958
  #rngSeed: 1111953
  rngSeed: 11153
  #rngSeed: 10590  
  #rngSeed: 51789
  #rngSeed: 1024 # rngSeed: 1111953
  #rngSeed: 102489 # rngSeed: 1111953
  #rngSeed: 11250 # rngSeed: 1111953
  #rngSeed: 6600 # rngSeed: 1111953
  #rngSeed: 101888
  #rngSeed: 10281991 #rngSeed: 102891
  # nostorm:
  #rngSeed: 61389
  #rngSeed: 6131989
  #rngSeed: 82985 # rngSeed: 8291985 
  #rngSeed: 10191989 # rngSeed: 5171989
  #rngSeed: 8311989 # rngSeed: 5171989
  startParID: 1
  stormFate: 2 # 0=use val from param list, 1=stormFate=false & stormUnk=True, 2=stormFAte=true, 3=false & stormUnk=False
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 3=100, 4=50, 0=use val from list
  mcType: 0 # 0=use val from param list, 1=fail, 2=unk
  rangeVar: 0
  saveNData: False
  mark: False
  mcmc: True
  # mcmc: False
  logex: True
  testing: "no"
  predict: False
  # survSave: "trueVal" # "all"=all DSR/PSR/SE vals; "trueVal"=just the "true" vals
  survSave: "all" # "all"=all DSR/PSR/SE vals; "trueVal"=just the "true" vals
  coefSave: "all"
  ndatSave: True
  plotPred: False
  obsSave: False
  predSave: False
  # survSave: "all"
  debug: 0
  debugLL: 4
  debugNests: 0
  debugM: 0
  debugObs: 4
  debugFlood: 0
  debugLogEx: 4
  debugDSR: 4
  debugSummary: 0
  optimizer: "trust-constr"
  optimGlob: False
  optimFunc: "scipy"
  # other: "high_sdecay"
  other: ""
  # addMC: False
  addMC: True
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

test:
  # nreps: 100
  nreps: 3 
  # nreps: 100
  # saveNData: True
  # optimizer: "L-BFGS-B"
  # optimizer: "SLSQP"
  # optimGlob: True
  # optimizer: "BFGS"
  # optimizer: "Nelder-Mead"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  #rngSeed: 1111953
  #rngSeed: 7131958
  #rngSeed: 82985
  #rngSeed: 102891
  # rngSeed: 10181988
  rngSeed: 613
  startParID: 1
  stormFate: 0 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 3=100, 4=50, 0=use val from list
  mcType: 0 # 0=use val from params; 1=hatch/fail; 2=unk
  rangeVar: 4 # 1=probSurv; 2=decayRate; 3=discProb; 4=stormFrq; 5=obsint
  saveNData: False
  mark: False
  # mcmc: False
  mcmc: True
  # logex: False
  logex: True
  predict: False
  testing: "yes"
  survSave: "all"

  coefSave: "all"
  ndatSave: True
  plotPred: False
  obsSave: False
  predSave: False
  debug: 2
  debugLL: 1 #mcmc
  debugLogEx: 3
  debugNests: 2 #nest creation
  debugM: 0 #mark
  debugObs: 4
  debugFlood: 0
  debugDSR: 4
  debugSummary: 0
  optimizer: "trust-constr"
  optimFunc: "scipy"
  optimGlob: False
  other: ""
  addMC: True
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out/test"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

#####
  # likeDir: "/home/wodehouse/Projects/sim_model/out"

ctrl:
  # nreps: 500
  nreps: 200
  # testing: "yes"
  #rngSeed: 8291985   #rngSeed: 6131989
  # rngSeed: 6131989   #rngSeed: 82985
  #rngSeed: 1051990
  #rngSeed: 5171989
  rngSeed: 3698752
  #rngSeed: 3710330
  ##storm control:
  # rngSeed: 810
  #rngSeed: 2007 
  startParID: 1
  stormFate: 0 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 3=100, 4=50, 0=use val from list
  mcType: 0 # 0=fail, 1=unk
  rangeVar: 0
  saveNData: False
  mark: False
  mcmc: True
  # mcmc: False
  logex: True
  predict: False
  testing: "no"
  survSave: "all"
  coefSave: "all"
  ndatSave: True
  plotPred: False
  obsSave: False
  predSave: False
  debug: 0
  debugLL: 1
  debugNests: 1 
  debugM: 0
  debugObs: 4
  debugFlood: 0
  debugLogEx: 1
  debugDSR: 1
  debugSummary: 0
  # optimizer: "Powell" optimizer: "SLSQP"
  # optimizer: "L-BFGS-B"
  # optimizer: "BFGS" optimizer: "Nelder-Mead" optimizer: "bfgs" optimizer: "nelder"
  optimizer: "trust-constr"
  optimFunc: "scipy"
  optimGlob: True
  other: ""
  addMC: False
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: True
  # likeDir: "/home/wodehouse/Projects/sim_model/out"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"
#
## nesting??
# debugging:
#   debug: 


# config = Config(nreps       = 500, 
# # config = Config(nreps       = 1, 
#                 debug       = False, 
#                 debugLL     = False, 
#                 debugNests  = False, 
#                 debugM      = False,
#                 debugObs    = False,
#                 debugFlood  = False,
#                 useWin      = False,
#                 # testing     = False,
#                 testing     = "no",
#                 fnUnique    = False,
#                 # likeFile    = fname[0], 
#                 likeFile    = " ",
#                 stormInit = "/home/wodehouse/Projects/sim_model/storm_init3.csv",
#                 likeDir = "/home/wodehouse/Projects/sim_model/out",
#                 colNames    = " ",
#                 # colNames    = fname[1],
#                 # numOut      = 21)
#                 # numOut      = 18)
#                 numOut      = 11)
