default:
  nreps: 2
  mark: False
  mcmc: True
  # mcmc: False
  logex: True
  testing: "yes"
  # optimizer: "Nelder-Mead"
  # optimizer: "SLSQP"
  # optimizer: "L-BFGS-B"
  # optimizer: "BFGS"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  rngSeed: 71358
  stormFate: 1 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 0=use val from list
  mcType: 0 # 1=fail, 2=unk
  rangeVar: 0
  saveNData: False
  predict: False
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  startParID: 1
  debug: 2
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugLogEx: 0
  debugDSR: 0
  debugSummary: 0
  optimizer: "trust-constr"
  optimGlob: True
  optimFunc: "scipy"
  other: ""
  msg: ""
  numOut: 11 # only used when saving ml vals to matrix
  mcmcOld: False
  mayfStart: True
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out/default"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

# NOTE: atype can be overridden with cmd line args, but sometimes not feasible
# NOTE:   (like when calling python from R)
# NOTE: actually doesn't make sense to assign atype in config when config
# NOTE:     is chosen based on atype...

full:
  # nreps: 300
  # nreps: 500
  nreps: 200
  mark: False
  # mcmc: False
  mcmc: True
  logex: True
  saveNData: False
  predict: False
  testing: "no"
  # optimizer: "Nelder-Mead"
  # optimizer: "SLSQP"
  # optimizer: "BFGS"
  # optimizer: "L-BFGS-B"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  #rngSeed: 1111953
  #rngSeed: 11153
  #rngSeed: 7131958
  rngSeed: 71358
  #rngSeed: 10281991
  #rngSeed: 6131989
  #rngSeed: 8291985 
  #rngSeed: 5171989
  #rngSeed: 10181988
  stormFate: 3 # 0=use val from param list, 1=false, 2=true, 3=false & stormUnk==True
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 0=use val from list
  mcType: 0 # 0=use val from param list, 1=fail, 2=unk
  rangeVar: 0
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  startParID: 1
  # predSave: "all"
  debug: 0
  debugLL: 4
  debugNests: 0
  debugM: 0
  debugObs: 4
  debugFlood: 0
  debugLogEx: 4
  debugDSR: 4
  debugSummary: 0
  optimizer: "trust-constr"
  optimGlob: False
  optimFunc: "scipy"
  other: ""
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

test:
  # nreps: 100
  nreps: 3 
  mark: False
  # mcmc: False
  mcmc: True
  logex: True
  # nreps: 100
  # saveNData: True
  saveNData: False
  predict: False
  testing: "yes"
  # optimizer: "L-BFGS-B"
  # optimizer: "SLSQP"
  # optimGlob: True
  # optimizer: "BFGS"
  # optimizer: "Nelder-Mead"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  #rngSeed: 1111953
  rngSeed: 7131958
  #rngSeed: 82985
  #rngSeed: 102891
  #rngSeed: 10181988
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  startParID: 1
  stormFate: 0 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 0=use val from list
  mcType: 0 # 0=use val from params; 1=hatch/fail; 2=unk
  rangeVar: 4 # 1=probSurv; 2=decayRate; 3=discProb; 4=stormFrq; 5=obsint
  debug: 2
  debugLL: 2 #mcmc
  debugNests: 3 #nest creation
  debugM: 0 #mark
  debugObs: 3
  debugFlood: 0
  debugLogEx: 2
  debugDSR: 2
  debugSummary: 0
  optimizer: "trust-constr"
  optimFunc: "scipy"
  optimGlob: False
  other: ""
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: False
  # likeDir: "/home/wodehouse/Projects/sim_model/out/test"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

#####
  # likeDir: "/home/wodehouse/Projects/sim_model/out"

ctrl:
  nreps: 500
  # nreps: 300
  mark: False
  mcmc: True
  # mcmc: False
  logex: True
  saveNData: False
  predict: False
  # testing: "yes"
  testing: "no"
  # optimizer: "Powell"
  # optimizer: "SLSQP"
  # optimizer: "L-BFGS-B"
  # optimizer: "BFGS"
  # optimizer: "Nelder-Mead"
  # optimizer: "bfgs"
  # optimizer: "nelder"
  #rngSeed: 82985
  #rngSeed: 6131989
  #rngSeed: 61389 rngSeed: 82985
  #rngSeed: 1051990
  rngSeed: 105199101
  stormFate: 0 # 0=use val from param list, 1=false, 2=true
  hTime: 0 #  0=use val from param list, 1=16, 2=20, 3=28
  numNests: 0 # 1=250, 2=500, 0=use val from list
  mcType: 0 # 0=fail, 1=unk
  rangeVar: 0
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  startParID: 1
  debug: 0
  debugLL: 4
  debugNests: 0 
  debugM: 0
  debugObs: 3
  debugFlood: 0
  debugLogEx: 4
  debugDSR: 4
  debugSummary: 0
  optimizer: "trust-constr"
  optimFunc: "scipy"
  optimGlob: True
  other: ""
  msg: ""
  numOut: 11
  mayfStart: False
  mcmcOld: False
  useWin: False
  fnUnique: True
  # likeDir: "/home/wodehouse/Projects/sim_model/out"
  # stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"
#
## nesting??
# debugging:
#   debug: 


# config = Config(nreps       = 500, 
# # config = Config(nreps       = 1, 
#                 debug       = False, 
#                 debugLL     = False, 
#                 debugNests  = False, 
#                 debugM      = False,
#                 debugObs    = False,
#                 debugFlood  = False,
#                 useWin      = False,
#                 # testing     = False,
#                 testing     = "no",
#                 fnUnique    = False,
#                 # likeFile    = fname[0], 
#                 likeFile    = " ",
#                 stormInit = "/home/wodehouse/Projects/sim_model/storm_init3.csv",
#                 likeDir = "/home/wodehouse/Projects/sim_model/out",
#                 colNames    = " ",
#                 # colNames    = fname[1],
#                 # numOut      = 21)
#                 # numOut      = 18)
#                 numOut      = 11)
