default:
  nreps: 1
  testing: "no"
  optimizer: "Nelder-Mead"
  rngSeed: 71358
  mayfStart: True
  stormFate: 0
  hTime: 3
  saveNData: False
  predict: False
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  debug: 0
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11 # only used when saving ml vals to matrix
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out/default"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

# NOTE: atype can be overridden with cmd line args, but sometimes not feasible
# NOTE:   (like when calling python from R)
# NOTE: actually doesn't make sense to assign atype in config when config
# NOTE:     is chosen based on atype...

full:
  nreps: 200
  saveNData: False
  predict: False
  testing: "no"
  optimizer: "Nelder-Mead"
  #rngSeed: 11153
  #rngSeed: 7131958
  rngSeed: 10281991
  #rngSeed: 82985
  mayfStart: False
  stormFate: 2 #0=false, 1=true, 2=use val from param list
  hTime: 2
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  # predSave: "all"
  debug: 0
  debugLL: 0
  debugNests: 0
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

test:
  nreps: 2 
  # nreps: 100
  # saveNData: True
  saveNData: False
  predict: False
  testing: "yes"
  #optimizer: "L-BFGS-B"
  optimizer: "Nelder-Mead"
  #rngSeed: 82985
  rngSeed: 102891
  #rngSeed: 10181988
  mayfStart: False
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  stormFate: 2
  hTime: 3
  debug: 3
  debugLL: 3
  debugNests: 1 
  debugM: 1
  debugObs: 1
  debugFlood: 1
  debugSummary: 3
  msg: ""
  numOut: 11
  useWin: False
  fnUnique: False
  likeDir: "/home/wodehouse/Projects/sim_model/out/test"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"

#####
  # likeDir: "/home/wodehouse/Projects/sim_model/out"

ctrl:
  nreps: 300
  saveNData: False
  predict: False
  testing: "no"
  # optimizer: "Powell"
  optimizer: "Nelder-Mead"
  rngSeed: 82985
  #rngSeed: 6131989
  #rngSeed: 5171989
  mayfStart: False
  stormFate: 2
  hTime: 3
  predSave: "none"
  coefSave: "none"
  obsSave: False
  plotPred: False
  debug: 0
  debugLL: 0
  debugNests: 0 
  debugM: 0
  debugObs: 0
  debugFlood: 0
  debugSummary: 0
  msg: ""
  numOut: 11
  useWin: False
  fnUnique: True
  likeDir: "/home/wodehouse/Projects/sim_model/out"
  stormInit: "/home/wodehouse/Projects/sim_model/storm_init3.csv"
#
## nesting??
# debugging:
#   debug: 


# config = Config(nreps       = 500, 
# # config = Config(nreps       = 1, 
#                 debug       = False, 
#                 debugLL     = False, 
#                 debugNests  = False, 
#                 debugM      = False,
#                 debugObs    = False,
#                 debugFlood  = False,
#                 useWin      = False,
#                 # testing     = False,
#                 testing     = "no",
#                 fnUnique    = False,
#                 # likeFile    = fname[0], 
#                 likeFile    = " ",
#                 stormInit = "/home/wodehouse/Projects/sim_model/storm_init3.csv",
#                 likeDir = "/home/wodehouse/Projects/sim_model/out",
#                 colNames    = " ",
#                 # colNames    = fname[1],
#                 # numOut      = 21)
#                 # numOut      = 18)
#                 numOut      = 11)
